version: "3.8"

services:
    vector_db:
        container_name: vector_db
        image: ankane/pgvector
        restart: always
        env_file:
            - .env
        environment:
            - POSTGRES_USER=${VECTOR_DB_USERNAME}
            - POSTGRES_PASSWORD=${VECTOR_DB_PASSWORD}
            - POSTGRES_DB=${VECTOR_DB_DATABASE}
            - PG_DATA=/var/lib/postgresql/data
        ports:
            - "${VECTOR_DB_PORT}:5432"
        volumes:
            - vector_pgdata:/var/lib/postgresql/data

volumes:
    vector_pgdata:
        driver: local
