name: Build and Deploy API Backend to Google Cloud

on:
    push:
        branches:
            - main

jobs:
    build:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Log in to Docker Hub
              run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

            - name: Build Docker image for API
              run: |
                  docker build -t ${{ secrets.DOCKER_USERNAME }}/jobcompass-ai-img:latest .

            - name: Push Docker image to Docker Hub
              run: |
                  docker push ${{ secrets.DOCKER_USERNAME }}/jobcompass-ai-img:latest

    deploy:
        needs: build
        runs-on: ubuntu-latest

        steps:
            - name: Setup SSH
              run: |
                  mkdir -p ~/.ssh
                  echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_rsa
                  chmod 600 ~/.ssh/id_rsa
                  ssh-keyscan -H ${{ secrets.SSH_HOST }} >> ~/.ssh/known_hosts

            - name: Deploy API AI to Server
              run: |
                  ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
                    echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin
                    sudo docker stop jobcompass-ai || true
                    sudo docker rm jobcompass-ai || true
                    sudo docker rmi ${{ secrets.DOCKER_USERNAME }}/jobcompass-ai-img:latest || true
                    sudo docker pull ${{ secrets.DOCKER_USERNAME }}/jobcompass-ai-img:latest
                    sudo docker run -d --name jobcompass-ai -p ${{ secrets.HOST_PORT }}:${{ secrets.CONTAINER_PORT }} --env-file ./ai-system/.env ${{ secrets.DOCKER_USERNAME }}/jobcompass-ai-img:latest
                  EOF
